// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'services/objectbox_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6318390828828842877),
      name: 'VectorEntity',
      lastPropertyId: const obx_int.IdUid(8, 4455189333580759326),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4219027748054193382),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7536595315597924566),
            name: 'filePath',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 178835215935560641)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9048125910512626036),
            name: 'fileName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1357191850355994586),
            name: 'fileType',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 4303950733721636113)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6583030224851664435),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1231340389765465001),
            name: 'vector',
            type: 28,
            flags: 8,
            indexId: const obx_int.IdUid(3, 944804239698216391),
            hnswParams: obx_int.ModelHnswParams(
              dimensions: 512,
              distanceType: 2,
            )),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6868865041641381178),
            name: 'indexedAt',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4455189333580759326),
            name: 'fileSize',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 6318390828828842877),
      lastIndexId: const obx_int.IdUid(3, 944804239698216391),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    VectorEntity: obx_int.EntityDefinition<VectorEntity>(
        model: _entities[0],
        toOneRelations: (VectorEntity object) => [],
        toManyRelations: (VectorEntity object) => {},
        getId: (VectorEntity object) => object.id,
        setId: (VectorEntity object, int id) {
          object.id = id;
        },
        objectToFB: (VectorEntity object, fb.Builder fbb) {
          final filePathOffset = object.filePath == null
              ? null
              : fbb.writeString(object.filePath!);
          final fileNameOffset = object.fileName == null
              ? null
              : fbb.writeString(object.fileName!);
          final fileTypeOffset = object.fileType == null
              ? null
              : fbb.writeString(object.fileType!);
          final contentOffset =
              object.content == null ? null : fbb.writeString(object.content!);
          final vectorOffset = object.vector == null
              ? null
              : fbb.writeListFloat32(object.vector!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, filePathOffset);
          fbb.addOffset(2, fileNameOffset);
          fbb.addOffset(3, fileTypeOffset);
          fbb.addOffset(4, contentOffset);
          fbb.addOffset(5, vectorOffset);
          fbb.addInt64(6, object.indexedAt);
          fbb.addInt64(7, object.fileSize);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = VectorEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..filePath = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6)
            ..fileName = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..fileType = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..content = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12)
            ..vector =
                const fb.ListReader<double>(fb.Float32Reader(), lazy: false)
                    .vTableGetNullable(buffer, rootOffset, 14)
            ..indexedAt =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16)
            ..fileSize = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 18);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [VectorEntity] entity fields to define ObjectBox queries.
class VectorEntity_ {
  /// See [VectorEntity.id].
  static final id =
      obx.QueryIntegerProperty<VectorEntity>(_entities[0].properties[0]);

  /// See [VectorEntity.filePath].
  static final filePath =
      obx.QueryStringProperty<VectorEntity>(_entities[0].properties[1]);

  /// See [VectorEntity.fileName].
  static final fileName =
      obx.QueryStringProperty<VectorEntity>(_entities[0].properties[2]);

  /// See [VectorEntity.fileType].
  static final fileType =
      obx.QueryStringProperty<VectorEntity>(_entities[0].properties[3]);

  /// See [VectorEntity.content].
  static final content =
      obx.QueryStringProperty<VectorEntity>(_entities[0].properties[4]);

  /// See [VectorEntity.vector].
  static final vector =
      obx.QueryHnswProperty<VectorEntity>(_entities[0].properties[5]);

  /// See [VectorEntity.indexedAt].
  static final indexedAt =
      obx.QueryIntegerProperty<VectorEntity>(_entities[0].properties[6]);

  /// See [VectorEntity.fileSize].
  static final fileSize =
      obx.QueryIntegerProperty<VectorEntity>(_entities[0].properties[7]);
}
